### ISSUE TITLE
Funciona en Nicaragua

### ISSUE THREAD

**Issue by ghost** [elaniin/BAC-Woocommerce-Plugin#3]
Funciona para Nicaragua. Seria excelente saber. Ya que ayudaría a muchos comercios.

**Comment by adriangomezme** [comment]
Hola @wbsnic , no lo hemos probado. Pero personas de Guatemala, Costa Rica, El Salvador lo han usado y les va bien, por lo que pienso que sí. Al final BAC maneja todo centralizado desde CR y su payment gateway es el mismo, así que en teoría sí debe de funcionar.
